### PR TITLE
Add greeting message and details about switching between learn and quiz mode

### LINKED ISSUE #26: Figure out how to clear GUI displaying without clearing stored data for v1.2.1
As per title.

This is helpful for v1.2, when we want to clear the previous displaying aftering entering a new mode. (e.g. go to study mode from learn mode, go back to learn mode from study mode)

### LINKED ISSUE #27: Figure out how to display some different content in GUI for v1.2.1
As per title.

This will be useful for displaying some welcome message after the app is initiated.

### PR DESCRIPTION
**Pull request by xinweit**

### CODE REVIEW

**Comment by Cheng20010201** [comment]
@xinweit after I merged my previous PR into the code base there seems to be a conflict. The conflict is in `MainWindow.java` and it seems its relatively simple to resolve from your side. Its a bit troublesome from my side as I would need to make changes of your PR locally, so can help?

You can resolve it by trying to pull the latest master branch to your GUI-display branch. Thx!! :)

**Comment by xinweit** [comment]
> @xinweit after I merged my previous PR into the code base there seems to be a conflict. The conflict is in `MainWindow.java` and it seems its relatively simple to resolve from your side. Its a bit troublesome from my side as I would need to make changes of your PR locally, so can help?
> 
> You can resolve it by trying to pull the latest master branch to your GUI-display branch. Thx!! :)

Sure bro ill do that, no prob

**Comment by xinweit** [comment]
updated

**Review by Cheng20010201 — APPROVED** [review]
LGTM
:D

**Pull request merged**
